[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-lang-starknet-classes = { git = "https://github.com/starkware-libs/cairo", rev = "86b6b559ea15359ffaf35b3aa6474836179c57ce" }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
